# ANA03 - TP Ejercicios Introducción a OpenCV II

Autor: Cader Fernanda

1.- Se pide:

- Genere una imagen de 150x150 pixeles de color rojo.

- Cambie el color 5 pixeles (al azar) a color blanco.

- Cambie el color de la imagen por un color a elección. Los pixeles de color blanco deben quedar en ese color.

- Visualice las dos imagenes.

- Guarde ambas imagenes: la primer con el nombre 'imagenRoja.png', la segunda con el nombre 'imagenNuevoColor.png'.

In [152]:
import numpy as np
import cv2

# Generamos una imagen roja de 150x150 píxeles
imagen_roja = np.zeros((150, 150, 3), np.uint8)
#Asignamos el color rojo a todos los píxeles de la imagen
imagen_roja[:] = (0, 0, 255)  # Rojo: BGR = (0, 0, 255)

print("Tipo de dato de la variable imagen_roja:",type(imagen_roja))
print("Contenido de la variable imagen_roja",imagen_roja)

Tipo de dato de la variable imagen_roja: <class 'numpy.ndarray'>
Contenido de la variable imagen_roja [[[  0   0 255]
  [  0   0 255]
  [  0   0 255]
  ...
  [  0   0 255]
  [  0   0 255]
  [  0   0 255]]

 [[  0   0 255]
  [  0   0 255]
  [  0   0 255]
  ...
  [  0   0 255]
  [  0   0 255]
  [  0   0 255]]

 [[  0   0 255]
  [  0   0 255]
  [  0   0 255]
  ...
  [  0   0 255]
  [  0   0 255]
  [  0   0 255]]

 ...

 [[  0   0 255]
  [  0   0 255]
  [  0   0 255]
  ...
  [  0   0 255]
  [  0   0 255]
  [  0   0 255]]

 [[  0   0 255]
  [  0   0 255]
  [  0   0 255]
  ...
  [  0   0 255]
  [  0   0 255]
  [  0   0 255]]

 [[  0   0 255]
  [  0   0 255]
  [  0   0 255]
  ...
  [  0   0 255]
  [  0   0 255]
  [  0   0 255]]]


In [153]:
# Cambiamos el color de 5 píxeles a blanco
for _ in range(5):
    x = np.random.randint(0, 150)
    y = np.random.randint(0, 150)
    imagen_roja[y, x] = (255, 255, 255)  # Blanco: BGR = (255, 255, 255)

In [154]:
# Generamos una imagen azul de 150x150 píxeles
imagen_azul = np.zeros((150, 150, 3), np.uint8)

#Asignamos el color azul a todos los píxeles de la imagen
imagen_azul[:] = (255, 0, 0)

In [155]:
# Cambiamos el color de 5 píxeles a blanco
for _ in range(5):
    x = np.random.randint(0, 150)
    y = np.random.randint(0, 150)
    imagen_azul[y, x] = (255, 255, 255)

In [156]:
# Mostrar las imágenes
cv2.imshow("Imagen Roja", imagen_roja)
cv2.imshow("Imagen Azul", imagen_azul)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [157]:
# Guardar las imágenes
cv2.imwrite("imagenRoja.png", imagen_roja)
cv2.imwrite("imagenNuevoColor.png", imagen_azul)

True

2.- Se pide:

- Genere una imagen de 600x1000 pixeles.

- Divida la imagen en rectangulos de 100x200 pixeles.

- Replique el código del ejemplo y añada mas colores y texto si necesita.

In [158]:
#Crearé una imagen de 600x1000 pixeles, con 3 canales de color (RGB) de 8 bits y lo rellenamos de ceros
from numpy import dtype

big = np.zeros((600,1000,3),dtype=np.uint8)

#Seleccionamos una fuente elegante

font = cv2.FONT_ITALIC

Generaré un abanico de colores amplio

In [159]:
# Dibujar rectángulos de diferentes colores
big[:100, :200] = (255, 0, 0)      # Azul
big[:100, 200:400] = (0, 165, 255)  # Naranja
big[:100, 400:600] = (0, 0, 255)    # Rojo
big[:100, 600:800] = (0, 255, 0)    # Verde
big[:100, 800:1000] = (255, 255, 0) # Cyan

# Agregar texto a la imagen
cv2.putText(big, 'Azul', (5, 55), font, 0.5, (255, 255, 255), 1, cv2.LINE_AA)
cv2.putText(big, 'Naranja', (220, 55), font, 0.5, (255, 255, 255), 1, cv2.LINE_AA)
cv2.putText(big, 'Rojo', (440, 55), font, 0.5, (255, 255, 255), 1, cv2.LINE_AA)
cv2.putText(big, 'Verde', (640, 55), font, 0.5, (255, 255, 255), 1, cv2.LINE_AA)
cv2.putText(big, 'Cyan', (840, 55), font, 0.5, (255, 255, 255), 1, cv2.LINE_AA)


array([[[255,   0,   0],
        [255,   0,   0],
        [255,   0,   0],
        ...,
        [255, 255,   0],
        [255, 255,   0],
        [255, 255,   0]],

       [[255,   0,   0],
        [255,   0,   0],
        [255,   0,   0],
        ...,
        [255, 255,   0],
        [255, 255,   0],
        [255, 255,   0]],

       [[255,   0,   0],
        [255,   0,   0],
        [255,   0,   0],
        ...,
        [255, 255,   0],
        [255, 255,   0],
        [255, 255,   0]],

       ...,

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]]

In [160]:
# Repetir el dibujo de rectángulos con diferentes colores para completar la imagen
big[100:200, :200] = (128, 0, 128)      # Púrpura
big[100:200, 200:400] = (255, 140, 0)   # Celeste
big[100:200, 400:600] = (139, 0, 139)   # Violeta
big[100:200, 600:800] = (255, 192, 203) # Rosa claro
big[100:200, 800:1000] = (0, 128, 128)  # Verde amarillento

# Agregar más texto a la imagen
cv2.putText(big, 'Purpura', (5, 155), font, 0.5, (255, 255, 255), 1, cv2.LINE_AA)
cv2.putText(big, 'Celeste', (220, 155), font, 0.5, (255, 255, 255), 1, cv2.LINE_AA)
cv2.putText(big, 'Violeta', (440, 155), font, 0.5, (255, 255, 255), 1, cv2.LINE_AA)
cv2.putText(big, 'Rosa claro', (640, 155), font, 0.5, (255, 255, 255), 1, cv2.LINE_AA)
cv2.putText(big, 'Verde amarillento', (840, 155), font, 0.5, (255, 255, 255), 1, cv2.LINE_AA)

array([[[255,   0,   0],
        [255,   0,   0],
        [255,   0,   0],
        ...,
        [255, 255,   0],
        [255, 255,   0],
        [255, 255,   0]],

       [[255,   0,   0],
        [255,   0,   0],
        [255,   0,   0],
        ...,
        [255, 255,   0],
        [255, 255,   0],
        [255, 255,   0]],

       [[255,   0,   0],
        [255,   0,   0],
        [255,   0,   0],
        ...,
        [255, 255,   0],
        [255, 255,   0],
        [255, 255,   0]],

       ...,

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]]

In [161]:
# Repetir el dibujo de rectángulos con diferentes colores para completar la imagen
big[200:300, :200] = (255, 0, 255)      
big[200:300, 200:400] = (128, 128, 0)   
big[200:300, 400:600] = (128, 0, 0)     
big[200:300, 600:800] = (128, 128, 128) 
big[200:300, 800:1000] = (0, 255, 255)  

cv2.putText(big, 'Magenta', (5, 255), font, 0.5, (255, 255, 255), 1, cv2.LINE_AA)
cv2.putText(big, 'Turquesa', (220, 255), font, 0.5, (255, 255, 255), 1, cv2.LINE_AA)
cv2.putText(big, 'Azul oscuro', (440, 255), font, 0.5, (255, 255, 255), 1, cv2.LINE_AA)
cv2.putText(big, 'Gris', (640, 255), font, 0.5, (255, 255, 255), 1, cv2.LINE_AA)
cv2.putText(big, 'Amarillo', (840, 255), font, 0.5, (0, 0, 0), 1, cv2.LINE_AA)

array([[[255,   0,   0],
        [255,   0,   0],
        [255,   0,   0],
        ...,
        [255, 255,   0],
        [255, 255,   0],
        [255, 255,   0]],

       [[255,   0,   0],
        [255,   0,   0],
        [255,   0,   0],
        ...,
        [255, 255,   0],
        [255, 255,   0],
        [255, 255,   0]],

       [[255,   0,   0],
        [255,   0,   0],
        [255,   0,   0],
        ...,
        [255, 255,   0],
        [255, 255,   0],
        [255, 255,   0]],

       ...,

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]]

In [162]:
big[300:400, :200] = (0, 0, 128)       
big[300:400, 200:400] = (128, 0, 255)  
big[300:400, 400:600] = (0, 128, 0)   
big[300:400, 600:800] = (255, 0, 128)  
big[300:400, 800:1000] = (0, 255, 128) 

cv2.putText(big, 'Bordo', (5, 355), font, 0.5, (255, 255, 255), 1, cv2.LINE_AA)
cv2.putText(big, 'Rosa Barbie', (220, 355), font, 0.5, (255, 255, 255), 1, cv2.LINE_AA)
cv2.putText(big, 'Verde oscuro', (440, 355), font, 0.5, (255, 255, 255), 1, cv2.LINE_AA)
cv2.putText(big, 'Violeta fuerte', (640, 355), font, 0.5, (255, 255, 255), 1, cv2.LINE_AA)
cv2.putText(big, 'Verde lima', (840, 355), font, 0.5, (255, 255, 255), 1, cv2.LINE_AA)

array([[[255,   0,   0],
        [255,   0,   0],
        [255,   0,   0],
        ...,
        [255, 255,   0],
        [255, 255,   0],
        [255, 255,   0]],

       [[255,   0,   0],
        [255,   0,   0],
        [255,   0,   0],
        ...,
        [255, 255,   0],
        [255, 255,   0],
        [255, 255,   0]],

       [[255,   0,   0],
        [255,   0,   0],
        [255,   0,   0],
        ...,
        [255, 255,   0],
        [255, 255,   0],
        [255, 255,   0]],

       ...,

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]]

In [163]:
# Repetir el proceso con colores diferentes
big[400:500, :200] = (95, 0, 0)       #Azul medianoche
big[400:500, 200:400] = (0, 100, 0)    # Verde mas oscuro
big[400:500, 400:600] = (0, 0, 128)    # Rojo mas oscuro
big[400:500, 600:800] = (128, 0, 110)  # Púrpura
big[400:500, 800:1000] = (255, 165, 0) # Océano

# Agregar más texto a la imagen
cv2.putText(big, 'Azul medianoche', (5, 455), font, 0.5, (255, 255, 255), 1, cv2.LINE_AA)
cv2.putText(big, 'Verde mas oscuro', (220, 455), font, 0.5, (255, 255, 255), 1, cv2.LINE_AA)
cv2.putText(big, 'Rojo mas oscuro', (440, 455), font, 0.5, (255, 255, 255), 1, cv2.LINE_AA)
cv2.putText(big, 'Purpura', (640, 455), font, 0.5, (255, 255, 255), 1, cv2.LINE_AA)
cv2.putText(big, 'Oceano', (840, 455), font, 0.5, (255, 255, 255), 1, cv2.LINE_AA)

array([[[255,   0,   0],
        [255,   0,   0],
        [255,   0,   0],
        ...,
        [255, 255,   0],
        [255, 255,   0],
        [255, 255,   0]],

       [[255,   0,   0],
        [255,   0,   0],
        [255,   0,   0],
        ...,
        [255, 255,   0],
        [255, 255,   0],
        [255, 255,   0]],

       [[255,   0,   0],
        [255,   0,   0],
        [255,   0,   0],
        ...,
        [255, 255,   0],
        [255, 255,   0],
        [255, 255,   0]],

       ...,

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]]

In [164]:
# Repetir el proceso con colores diferentes
big[500:600, :200] = (255, 255, 255) # Blanco
big[500:600, 200:400] = (128, 128, 128) # Gris
big[500:600, 400:600] = (0, 255, 255) # Amarillo
big[500:600, 600:800] = (255, 0, 255) # Magenta
big[500:600, 800:1000] = (0, 0, 0) # Negro

# Agregar más texto a la imagen
cv2.putText(big, 'Blanco', (5, 555), font, 0.5, (0, 0, 0), 1, cv2.LINE_AA)
cv2.putText(big, 'Gris', (220, 555), font, 0.5, (255, 255, 255), 1, cv2.LINE_AA)
cv2.putText(big, 'Amarillo', (440, 555), font, 0.5, (0, 0, 0), 1, cv2.LINE_AA)
cv2.putText(big, 'Magenta', (640, 555), font, 0.5, (255, 255, 255), 1, cv2.LINE_AA)
cv2.putText(big, 'Negro', (840, 555), font, 0.5, (255, 255, 255), 1, cv2.LINE_AA)

array([[[255,   0,   0],
        [255,   0,   0],
        [255,   0,   0],
        ...,
        [255, 255,   0],
        [255, 255,   0],
        [255, 255,   0]],

       [[255,   0,   0],
        [255,   0,   0],
        [255,   0,   0],
        ...,
        [255, 255,   0],
        [255, 255,   0],
        [255, 255,   0]],

       [[255,   0,   0],
        [255,   0,   0],
        [255,   0,   0],
        ...,
        [255, 255,   0],
        [255, 255,   0],
        [255, 255,   0]],

       ...,

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]]

In [165]:
cv2.imshow('previsualizacion', big)
cv2.waitKey(0)
cv2.destroyAllWindows()

3.- Dada la imagen 'deportes.png'

Divida la imagen en la cantidad que considere adecuada.

Con las imagenes generadas, cree nuevas imagenes que sean combinación de las anteriores (todas las combinaciones posibles).

Guarde cada una de las imagenes generadas de la combinación.

In [166]:
# Leemos la imagen

img = cv2.imread("deportes.png")

# Obtenemos las dimensiones de la imagen, esto con el atributo shape,filas,columnas y canales
alto,largo,_canales = img.shape
print(largo,alto)

1920 1080


In [167]:
#La imagen es de 1920x1080, con estas medidas vamos a crear imagenes nuevas calculando el ancho de cada tercio, 
#ya que la imagen son 3 deportes diferentes

# Calculamos el ancho de cada tercio
ancho_tercio = largo // 3

# Obtenemos los píxeles de cada tercio horizontalmente
tercio1 = img[0:alto, 0:ancho_tercio]
tercio2 = img[0:alto, ancho_tercio:2*ancho_tercio]
tercio3 = img[0:alto, 2*ancho_tercio:]



In [168]:
# Creamos una imagen compuesta
imagen_compuesta = np.zeros((alto, largo, 3), np.uint8)

# Asignamos los píxeles de cada tercio a la imagen compuesta en un orden diferente
imagen_compuesta[0:alto, 0:ancho_tercio] = tercio3
imagen_compuesta[0:alto, ancho_tercio:2*ancho_tercio] = tercio1
imagen_compuesta[0:alto, 2*ancho_tercio:] = tercio2

In [169]:
# Mostrar imágenes
cv2.namedWindow("Tercio1", cv2.WINDOW_NORMAL)
cv2.namedWindow("Tercio2", cv2.WINDOW_NORMAL)
cv2.namedWindow("Tercio3", cv2.WINDOW_NORMAL)
cv2.namedWindow("Compuesta", cv2.WINDOW_NORMAL)
cv2.imshow("Tercio1", tercio1)
cv2.imshow("Tercio2", tercio2)
cv2.imshow("Tercio3", tercio3)
cv2.imshow("Compuesta", imagen_compuesta)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [170]:
# Guardar la imagen compuesta
cv2.imwrite('imagenCompuesta.png', imagen_compuesta)

True